// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: pkg/proto/sim/sim-service.proto

package sim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "orbital-net/pkg/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_SATELLITE NodeType = 0
	NodeType_STATION   NodeType = 1
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "SATELLITE",
		1: "STATION",
	}
	NodeType_value = map[string]int32{
		"SATELLITE": 0,
		"STATION":   1,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_sim_sim_service_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_pkg_proto_sim_sim_service_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_sim_sim_service_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sim_sim_service_proto_rawDescGZIP(), []int{0}
}

type SimulationState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nodes         []*common.Node         `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationState) Reset() {
	*x = SimulationState{}
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationState) ProtoMessage() {}

func (x *SimulationState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationState.ProtoReflect.Descriptor instead.
func (*SimulationState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sim_sim_service_proto_rawDescGZIP(), []int{1}
}

func (x *SimulationState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SimulationState) GetNodes() []*common.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type CreateNodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Altitude       float64                `protobuf:"fixed64,2,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Angle          float64                `protobuf:"fixed64,3,opt,name=angle,proto3" json:"angle,omitempty"`
	Type           NodeType               `protobuf:"varint,4,opt,name=type,proto3,enum=sim.NodeType" json:"type,omitempty"`
	PortQuantity   int32                  `protobuf:"varint,5,opt,name=port_quantity,json=portQuantity,proto3" json:"port_quantity,omitempty"`
	PortGeneration int32                  `protobuf:"varint,6,opt,name=port_generation,json=portGeneration,proto3" json:"port_generation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sim_sim_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeRequest) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *CreateNodeRequest) GetAngle() float64 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *CreateNodeRequest) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_SATELLITE
}

func (x *CreateNodeRequest) GetPortQuantity() int32 {
	if x != nil {
		return x.PortQuantity
	}
	return 0
}

func (x *CreateNodeRequest) GetPortGeneration() int32 {
	if x != nil {
		return x.PortGeneration
	}
	return 0
}

type CreateNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeResponse) Reset() {
	*x = CreateNodeResponse{}
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeResponse) ProtoMessage() {}

func (x *CreateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sim_sim_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sim_sim_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DeleteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeResponse) Reset() {
	*x = DeleteNodeResponse{}
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResponse) ProtoMessage() {}

func (x *DeleteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sim_sim_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sim_sim_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_proto_sim_sim_service_proto protoreflect.FileDescriptor

const file_pkg_proto_sim_sim_service_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/sim/sim-service.proto\x12\x03sim\x1a\x1cpkg/proto/common/model.proto\"\a\n" +
	"\x05Empty\"S\n" +
	"\x0fSimulationState\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\"\n" +
	"\x05nodes\x18\x02 \x03(\v2\f.common.NodeR\x05nodes\"\xca\x01\n" +
	"\x11CreateNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\baltitude\x18\x02 \x01(\x01R\baltitude\x12\x14\n" +
	"\x05angle\x18\x03 \x01(\x01R\x05angle\x12!\n" +
	"\x04type\x18\x04 \x01(\x0e2\r.sim.NodeTypeR\x04type\x12#\n" +
	"\rport_quantity\x18\x05 \x01(\x05R\fportQuantity\x12'\n" +
	"\x0fport_generation\x18\x06 \x01(\x05R\x0eportGeneration\"G\n" +
	"\x12CreateNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\",\n" +
	"\x11DeleteNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\".\n" +
	"\x12DeleteNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*&\n" +
	"\bNodeType\x12\r\n" +
	"\tSATELLITE\x10\x00\x12\v\n" +
	"\aSTATION\x10\x012\xf4\x01\n" +
	"\x11SimulationService\x126\n" +
	"\x10StreamSimulation\x12\n" +
	".sim.Empty\x1a\x14.sim.SimulationState0\x01\x12=\n" +
	"\n" +
	"CreateNode\x12\x16.sim.CreateNodeRequest\x1a\x17.sim.CreateNodeResponse\x12=\n" +
	"\n" +
	"DeleteNode\x12\x16.sim.DeleteNodeRequest\x1a\x17.sim.DeleteNodeResponse\x12)\n" +
	"\x0fClearSimulation\x12\n" +
	".sim.Empty\x1a\n" +
	".sim.EmptyB\x1bZ\x19orbital-net/pkg/proto/simb\x06proto3"

var (
	file_pkg_proto_sim_sim_service_proto_rawDescOnce sync.Once
	file_pkg_proto_sim_sim_service_proto_rawDescData []byte
)

func file_pkg_proto_sim_sim_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_sim_sim_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_sim_sim_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_sim_sim_service_proto_rawDesc), len(file_pkg_proto_sim_sim_service_proto_rawDesc)))
	})
	return file_pkg_proto_sim_sim_service_proto_rawDescData
}

var file_pkg_proto_sim_sim_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_sim_sim_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_sim_sim_service_proto_goTypes = []any{
	(NodeType)(0),              // 0: sim.NodeType
	(*Empty)(nil),              // 1: sim.Empty
	(*SimulationState)(nil),    // 2: sim.SimulationState
	(*CreateNodeRequest)(nil),  // 3: sim.CreateNodeRequest
	(*CreateNodeResponse)(nil), // 4: sim.CreateNodeResponse
	(*DeleteNodeRequest)(nil),  // 5: sim.DeleteNodeRequest
	(*DeleteNodeResponse)(nil), // 6: sim.DeleteNodeResponse
	(*common.Node)(nil),        // 7: common.Node
}
var file_pkg_proto_sim_sim_service_proto_depIdxs = []int32{
	7, // 0: sim.SimulationState.nodes:type_name -> common.Node
	0, // 1: sim.CreateNodeRequest.type:type_name -> sim.NodeType
	1, // 2: sim.SimulationService.StreamSimulation:input_type -> sim.Empty
	3, // 3: sim.SimulationService.CreateNode:input_type -> sim.CreateNodeRequest
	5, // 4: sim.SimulationService.DeleteNode:input_type -> sim.DeleteNodeRequest
	1, // 5: sim.SimulationService.ClearSimulation:input_type -> sim.Empty
	2, // 6: sim.SimulationService.StreamSimulation:output_type -> sim.SimulationState
	4, // 7: sim.SimulationService.CreateNode:output_type -> sim.CreateNodeResponse
	6, // 8: sim.SimulationService.DeleteNode:output_type -> sim.DeleteNodeResponse
	1, // 9: sim.SimulationService.ClearSimulation:output_type -> sim.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_sim_sim_service_proto_init() }
func file_pkg_proto_sim_sim_service_proto_init() {
	if File_pkg_proto_sim_sim_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_sim_sim_service_proto_rawDesc), len(file_pkg_proto_sim_sim_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_sim_sim_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_sim_sim_service_proto_depIdxs,
		EnumInfos:         file_pkg_proto_sim_sim_service_proto_enumTypes,
		MessageInfos:      file_pkg_proto_sim_sim_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_sim_sim_service_proto = out.File
	file_pkg_proto_sim_sim_service_proto_goTypes = nil
	file_pkg_proto_sim_sim_service_proto_depIdxs = nil
}
