// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: pkg/proto/common/model.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	X              float64                `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y              float64                `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Speed          float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Altitude       float64                `protobuf:"fixed64,6,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Angle          float64                `protobuf:"fixed64,7,opt,name=angle,proto3" json:"angle,omitempty"`
	VisiblePeers   []string               `protobuf:"bytes,8,rep,name=visible_peers,json=visiblePeers,proto3" json:"visible_peers,omitempty"`
	PortQuantity   int32                  `protobuf:"varint,9,opt,name=port_quantity,json=portQuantity,proto3" json:"port_quantity,omitempty"`
	PortGeneration int32                  `protobuf:"varint,10,opt,name=port_generation,json=portGeneration,proto3" json:"port_generation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_pkg_proto_common_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_common_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pkg_proto_common_model_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Node) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Node) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Node) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Node) GetAngle() float64 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *Node) GetVisiblePeers() []string {
	if x != nil {
		return x.VisiblePeers
	}
	return nil
}

func (x *Node) GetPortQuantity() int32 {
	if x != nil {
		return x.PortQuantity
	}
	return 0
}

func (x *Node) GetPortGeneration() int32 {
	if x != nil {
		return x.PortGeneration
	}
	return 0
}

var File_pkg_proto_common_model_proto protoreflect.FileDescriptor

const file_pkg_proto_common_model_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/proto/common/model.proto\x12\x06common\"\x81\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x03 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x01R\x01y\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x1a\n" +
	"\baltitude\x18\x06 \x01(\x01R\baltitude\x12\x14\n" +
	"\x05angle\x18\a \x01(\x01R\x05angle\x12#\n" +
	"\rvisible_peers\x18\b \x03(\tR\fvisiblePeers\x12#\n" +
	"\rport_quantity\x18\t \x01(\x05R\fportQuantity\x12'\n" +
	"\x0fport_generation\x18\n" +
	" \x01(\x05R\x0eportGenerationB\x1eZ\x1corbital-net/pkg/proto/commonb\x06proto3"

var (
	file_pkg_proto_common_model_proto_rawDescOnce sync.Once
	file_pkg_proto_common_model_proto_rawDescData []byte
)

func file_pkg_proto_common_model_proto_rawDescGZIP() []byte {
	file_pkg_proto_common_model_proto_rawDescOnce.Do(func() {
		file_pkg_proto_common_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_common_model_proto_rawDesc), len(file_pkg_proto_common_model_proto_rawDesc)))
	})
	return file_pkg_proto_common_model_proto_rawDescData
}

var file_pkg_proto_common_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_common_model_proto_goTypes = []any{
	(*Node)(nil), // 0: common.Node
}
var file_pkg_proto_common_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_common_model_proto_init() }
func file_pkg_proto_common_model_proto_init() {
	if File_pkg_proto_common_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_common_model_proto_rawDesc), len(file_pkg_proto_common_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_common_model_proto_goTypes,
		DependencyIndexes: file_pkg_proto_common_model_proto_depIdxs,
		MessageInfos:      file_pkg_proto_common_model_proto_msgTypes,
	}.Build()
	File_pkg_proto_common_model_proto = out.File
	file_pkg_proto_common_model_proto_goTypes = nil
	file_pkg_proto_common_model_proto_depIdxs = nil
}
