apiVersion: v1
kind: Service
metadata:
  name: communications-server
spec:
  selector:
    app: orbital-communications
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: communications-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbital-communications
  template:
    metadata:
      labels:
        app: orbital-communications
    spec:
      containers:
        - name: communications
          image: communications-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50053
          resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
          env:
            - name: SERVER_HOST
              value: "sim-server"
          command: ["./communications-bin"]
