apiVersion: v1
kind: Service
metadata:
  name: control-center
spec:
  selector:
    app: orbital-control
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbital-control
  template:
    metadata:
      labels:
        app: orbital-control
    spec:
      containers:
        - name: web
          image: control-center-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_HOST
              value: "sim-server"