apiVersion: v1
kind: Service
metadata:
  name: storage-server
spec:
  selector:
    app: orbital-storage
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbital-storage
  template:
    metadata:
      labels:
        app: orbital-storage
    spec:
      containers:
        - name: storage
          image: storage-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50054
          volumeMounts:
            - mountPath: /data
              name: data-vol
      volumes:
        - name: data-vol
          emptyDir: {}