// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: pkg/proto/pathfinder/pathfinder-service.proto

package pathfinder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PathfinderService_FindPath_FullMethodName = "/pathfinder.PathfinderService/FindPath"
)

// PathfinderServiceClient is the client API for PathfinderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PathfinderServiceClient interface {
	FindPath(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*PathResponse, error)
}

type pathfinderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPathfinderServiceClient(cc grpc.ClientConnInterface) PathfinderServiceClient {
	return &pathfinderServiceClient{cc}
}

func (c *pathfinderServiceClient) FindPath(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*PathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PathResponse)
	err := c.cc.Invoke(ctx, PathfinderService_FindPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PathfinderServiceServer is the server API for PathfinderService service.
// All implementations must embed UnimplementedPathfinderServiceServer
// for forward compatibility.
type PathfinderServiceServer interface {
	FindPath(context.Context, *PathRequest) (*PathResponse, error)
	mustEmbedUnimplementedPathfinderServiceServer()
}

// UnimplementedPathfinderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPathfinderServiceServer struct{}

func (UnimplementedPathfinderServiceServer) FindPath(context.Context, *PathRequest) (*PathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPath not implemented")
}
func (UnimplementedPathfinderServiceServer) mustEmbedUnimplementedPathfinderServiceServer() {}
func (UnimplementedPathfinderServiceServer) testEmbeddedByValue()                           {}

// UnsafePathfinderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PathfinderServiceServer will
// result in compilation errors.
type UnsafePathfinderServiceServer interface {
	mustEmbedUnimplementedPathfinderServiceServer()
}

func RegisterPathfinderServiceServer(s grpc.ServiceRegistrar, srv PathfinderServiceServer) {
	// If the following call pancis, it indicates UnimplementedPathfinderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PathfinderService_ServiceDesc, srv)
}

func _PathfinderService_FindPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathfinderServiceServer).FindPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathfinderService_FindPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathfinderServiceServer).FindPath(ctx, req.(*PathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PathfinderService_ServiceDesc is the grpc.ServiceDesc for PathfinderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PathfinderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pathfinder.PathfinderService",
	HandlerType: (*PathfinderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindPath",
			Handler:    _PathfinderService_FindPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/pathfinder/pathfinder-service.proto",
}
