// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: pkg/proto/pathfinder/pathfinder-service.proto

package pathfinder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartNodeId   string                 `protobuf:"bytes,1,opt,name=start_node_id,json=startNodeId,proto3" json:"start_node_id,omitempty"`
	EndNodeId     string                 `protobuf:"bytes,2,opt,name=end_node_id,json=endNodeId,proto3" json:"end_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	mi := &file_pkg_proto_pathfinder_pathfinder_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pathfinder_pathfinder_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pathfinder_pathfinder_service_proto_rawDescGZIP(), []int{0}
}

func (x *PathRequest) GetStartNodeId() string {
	if x != nil {
		return x.StartNodeId
	}
	return ""
}

func (x *PathRequest) GetEndNodeId() string {
	if x != nil {
		return x.EndNodeId
	}
	return ""
}

type PathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	PathNodeIds   []string               `protobuf:"bytes,2,rep,name=path_node_ids,json=pathNodeIds,proto3" json:"path_node_ids,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathResponse) Reset() {
	*x = PathResponse{}
	mi := &file_pkg_proto_pathfinder_pathfinder_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathResponse) ProtoMessage() {}

func (x *PathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pathfinder_pathfinder_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathResponse.ProtoReflect.Descriptor instead.
func (*PathResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pathfinder_pathfinder_service_proto_rawDescGZIP(), []int{1}
}

func (x *PathResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *PathResponse) GetPathNodeIds() []string {
	if x != nil {
		return x.PathNodeIds
	}
	return nil
}

func (x *PathResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_proto_pathfinder_pathfinder_service_proto protoreflect.FileDescriptor

const file_pkg_proto_pathfinder_pathfinder_service_proto_rawDesc = "" +
	"\n" +
	"-pkg/proto/pathfinder/pathfinder-service.proto\x12\n" +
	"pathfinder\"Q\n" +
	"\vPathRequest\x12\"\n" +
	"\rstart_node_id\x18\x01 \x01(\tR\vstartNodeId\x12\x1e\n" +
	"\vend_node_id\x18\x02 \x01(\tR\tendNodeId\"m\n" +
	"\fPathResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\"\n" +
	"\rpath_node_ids\x18\x02 \x03(\tR\vpathNodeIds\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2R\n" +
	"\x11PathfinderService\x12=\n" +
	"\bFindPath\x12\x17.pathfinder.PathRequest\x1a\x18.pathfinder.PathResponseB\"Z orbital-net/pkg/proto/pathfinderb\x06proto3"

var (
	file_pkg_proto_pathfinder_pathfinder_service_proto_rawDescOnce sync.Once
	file_pkg_proto_pathfinder_pathfinder_service_proto_rawDescData []byte
)

func file_pkg_proto_pathfinder_pathfinder_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_pathfinder_pathfinder_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_pathfinder_pathfinder_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_pathfinder_pathfinder_service_proto_rawDesc), len(file_pkg_proto_pathfinder_pathfinder_service_proto_rawDesc)))
	})
	return file_pkg_proto_pathfinder_pathfinder_service_proto_rawDescData
}

var file_pkg_proto_pathfinder_pathfinder_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_pathfinder_pathfinder_service_proto_goTypes = []any{
	(*PathRequest)(nil),  // 0: pathfinder.PathRequest
	(*PathResponse)(nil), // 1: pathfinder.PathResponse
}
var file_pkg_proto_pathfinder_pathfinder_service_proto_depIdxs = []int32{
	0, // 0: pathfinder.PathfinderService.FindPath:input_type -> pathfinder.PathRequest
	1, // 1: pathfinder.PathfinderService.FindPath:output_type -> pathfinder.PathResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_pathfinder_pathfinder_service_proto_init() }
func file_pkg_proto_pathfinder_pathfinder_service_proto_init() {
	if File_pkg_proto_pathfinder_pathfinder_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_pathfinder_pathfinder_service_proto_rawDesc), len(file_pkg_proto_pathfinder_pathfinder_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_pathfinder_pathfinder_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_pathfinder_pathfinder_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_pathfinder_pathfinder_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_pathfinder_pathfinder_service_proto = out.File
	file_pkg_proto_pathfinder_pathfinder_service_proto_goTypes = nil
	file_pkg_proto_pathfinder_pathfinder_service_proto_depIdxs = nil
}
