// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: pkg/proto/communications/communications-service.proto

package communications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginId      string                 `protobuf:"bytes,1,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	DestinationId string                 `protobuf:"bytes,2,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_pkg_proto_communications_communications_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_communications_communications_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_communications_communications_service_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

func (x *MessageRequest) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *MessageRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_pkg_proto_communications_communications_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_communications_communications_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_communications_communications_service_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_communications_communications_service_proto protoreflect.FileDescriptor

const file_pkg_proto_communications_communications_service_proto_rawDesc = "" +
	"\n" +
	"5pkg/proto/communications/communications-service.proto\x12\x0ecommunications\"n\n" +
	"\x0eMessageRequest\x12\x1b\n" +
	"\torigin_id\x18\x01 \x01(\tR\boriginId\x12%\n" +
	"\x0edestination_id\x18\x02 \x01(\tR\rdestinationId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"E\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2g\n" +
	"\x15CommunicationsService\x12N\n" +
	"\vSendMessage\x12\x1e.communications.MessageRequest\x1a\x1f.communications.MessageResponseB&Z$orbital-net/pkg/proto/communicationsb\x06proto3"

var (
	file_pkg_proto_communications_communications_service_proto_rawDescOnce sync.Once
	file_pkg_proto_communications_communications_service_proto_rawDescData []byte
)

func file_pkg_proto_communications_communications_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_communications_communications_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_communications_communications_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_communications_communications_service_proto_rawDesc), len(file_pkg_proto_communications_communications_service_proto_rawDesc)))
	})
	return file_pkg_proto_communications_communications_service_proto_rawDescData
}

var file_pkg_proto_communications_communications_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_communications_communications_service_proto_goTypes = []any{
	(*MessageRequest)(nil),  // 0: communications.MessageRequest
	(*MessageResponse)(nil), // 1: communications.MessageResponse
}
var file_pkg_proto_communications_communications_service_proto_depIdxs = []int32{
	0, // 0: communications.CommunicationsService.SendMessage:input_type -> communications.MessageRequest
	1, // 1: communications.CommunicationsService.SendMessage:output_type -> communications.MessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_communications_communications_service_proto_init() }
func file_pkg_proto_communications_communications_service_proto_init() {
	if File_pkg_proto_communications_communications_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_communications_communications_service_proto_rawDesc), len(file_pkg_proto_communications_communications_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_communications_communications_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_communications_communications_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_communications_communications_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_communications_communications_service_proto = out.File
	file_pkg_proto_communications_communications_service_proto_goTypes = nil
	file_pkg_proto_communications_communications_service_proto_depIdxs = nil
}
