// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: pkg/proto/communications/communications-service.proto

package communications

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommunicationsService_SendMessage_FullMethodName = "/communications.CommunicationsService/SendMessage"
)

// CommunicationsServiceClient is the client API for CommunicationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunicationsServiceClient interface {
	SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type communicationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunicationsServiceClient(cc grpc.ClientConnInterface) CommunicationsServiceClient {
	return &communicationsServiceClient{cc}
}

func (c *communicationsServiceClient) SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, CommunicationsService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationsServiceServer is the server API for CommunicationsService service.
// All implementations must embed UnimplementedCommunicationsServiceServer
// for forward compatibility.
type CommunicationsServiceServer interface {
	SendMessage(context.Context, *MessageRequest) (*MessageResponse, error)
	mustEmbedUnimplementedCommunicationsServiceServer()
}

// UnimplementedCommunicationsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommunicationsServiceServer struct{}

func (UnimplementedCommunicationsServiceServer) SendMessage(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedCommunicationsServiceServer) mustEmbedUnimplementedCommunicationsServiceServer() {}
func (UnimplementedCommunicationsServiceServer) testEmbeddedByValue()                               {}

// UnsafeCommunicationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunicationsServiceServer will
// result in compilation errors.
type UnsafeCommunicationsServiceServer interface {
	mustEmbedUnimplementedCommunicationsServiceServer()
}

func RegisterCommunicationsServiceServer(s grpc.ServiceRegistrar, srv CommunicationsServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommunicationsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommunicationsService_ServiceDesc, srv)
}

func _CommunicationsService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationsServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunicationsService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationsServiceServer).SendMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommunicationsService_ServiceDesc is the grpc.ServiceDesc for CommunicationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommunicationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "communications.CommunicationsService",
	HandlerType: (*CommunicationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _CommunicationsService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/communications/communications-service.proto",
}
